### ISSUE TITLE
Overriding variables

### ISSUE THREAD

**Issue by edublancas** [ploomber/soorgeon#11]
(i think this is already covered but I need to make sure and add a few tests)

**Important**: for these examples comments are H2 headings (e.g. `# I'm an H2 heading`)

We have to add two test cases:

### 1. Overriding variables

```python

# first

df = something()

# second

df = another()

# third

df_2 = df + 1
```

When running `soorgeon refactor`, the output should contain three notebooks (first, second, third). third.ipynb must contain the following:

```python
# third

df_2 = df + 1
```
Now, third uses `df` as input. So we must ensure that soorgeon picks up the `df` from the second notebook and not the one from the first one. Graphically it should be:

```mermaid
  graph LR;
      first;
      second --> third;
```

### Overriding variables (same cell)

```python
# first
df = something()

# second
df = another()
df_2 = df + 1
```

We need to ensure that in this case, the second task generated does not create a dependency with the first task, since it has its own `df` (i.e., it does not depend on the `df = something()` line).

In other words, the output pipeline (produced by `ploomber plot`), should look like this (two independent tasks):

```mermaid
  graph LR;
      first;
      second;
```

Instead of this (two dependent tasks):

```mermaid
  graph LR;
      first --> second;
```

### testing

the simplest way to test it is to call `soorgeon refactor` and then load the pipeline to ensure we got the right structure:

```python
from ploomber.spec import DAGSpec

nb = """
# notebook content goes here
"""

# refactor notebook
export.from_nb(_read(nb))

dag = DAGSpec('pipeline.yaml').to_dag().render()

# write assert statements for each task in the pipeline
# to get the task names, you can do:
list(dag)

# example, check that task_name only has one upstream dependency called 'get'
assert  set(dag['task_name'].upstream) == {'get'}

# another example, check that another_task has no dependencies
assert  set(dag['another_task'].upstream) == set()
```

**Comment by e1ha** [comment]
Is my task to create test cases to ensure that the df_2 does not use the previous (farther) df variable but the closer one? And if so, what files in soorgeon should I be creating the tests for?

**Comment by idomic** [comment]
So currently Soorgeon code doesn't do what's stated above.

We need to start with writing a few tests for this exact example, a notebook with 2 variables that override each other through the same name.
Then we need to adjust the code to make sure we deal with this case, meaning we assign the latest value to it, while translating the notebook (through `soorgeon refactor`).

Finally, we need to print to the user a yellow message through `click.secho` saying this happened and that they should be aware of it.

**Comment by idomic** [comment]
@edublancas don't we want soorgeon to also remove the redundant line?
i.e
from:
```
df = something()

# H2 header
df = another()
```

Since df is overwritten the first line is redundant, removing it will improve the code quality

**Comment by idomic** [comment]
Good point!

**Comment by e1ha** [comment]
I tested the first case and it uses the latest df for df_2. How should I determine where to add the code to print the user a yellow message for the duplicate assignments? Should I just look through all the files in soorgeon?

**Comment by e1ha** [comment]
also for the second case, what does it mean by "second proto-task does not create a dependency with the first proto-task"? Would I just be testing something similar as in the first case in that df_2 should be assigned to another() + 1 instead of something() + 1?

**Comment by edublancas** [comment]
welcome @e1ha! As a first step, I'd recommend you to go through the basics of soorgeon and ploomber. that will give you an overview of how they work, and implementing the tests will be easier.

soorgeon's guide: https://github.com/ploomber/soorgeon/blob/main/doc/guide.md

ploomber's guide: https://docs.ploomber.io/en/latest/get-started/quick-start.html

please go over these materials. We can use our meeting tomorrow to answer your questions

> I tested the first case and it uses the latest df for df_2. 

can you add a unit test? check out [this one](https://github.com/ploomber/soorgeon/blob/ac3f6e6df0f4cee0be444dbace544565b31cfb43/tests/test_export.py#L310). you'd have to implement a similar test: call `.export()` and then tests the contents of the generated files.

> How should I determine where to add the code to print the user a yellow message for the duplicate assignments?

this one is a bit more challenging, so let's work on it until the end

> also for the second case, what does it mean by "second proto-task does not create a dependency with the first proto-task"? Would I just be testing something similar as in the first case in that df_2 should be assigned to another() + 1 instead of something() + 1?

I re-wrote the initial comment for clarity.

**Comment by e1ha** [comment]
Hi I'm struggling with the test case for case 1 and would like some guidance. Currently in the code, I'm thinking of creating this  basic jupyter file: 
`"""# ## Load df

df = 1

# ## load df again

df = 5

# ## load df-2

df_2 = df + 1
"""`
After I call soorgeon refactor on this file (which I think is done by calling export.from_nb(...)), it should create 3 separate jupyter notebooks in the tasks folder. Then when we run the code and print out df_2 it should be 6 and not 3. Any comments or suggestions on whether this is the right track? Thanks.

**Comment by idomic** [comment]
> # ## Load df

Is this supposed to be an H2 heading?

Sounds like the right direction overall!
You can run the tests from the IDE or using [pytest](https://stackoverflow.com/questions/36456920/is-there-a-way-to-specify-which-pytest-tests-to-run-from-a-file)

You should also have another test case, besides this 3 headers case (you can parameterize your test to deal with multiple inputs like the snippet below)

```
@pytest.mark.parametrize("test_input,expected", [("3+5", 8), ("2+4", 6), ("6*9", 42)])
def test_eval(test_input, expected):
    assert eval(test_input) == expected
```

**Comment by e1ha** [comment]
Yes that's supposed to be an H2 heading.

**Comment by e1ha** [comment]
Would you guys mind taking a look at my test for case 1 to see if I'm doing it correctly?

**Comment by idomic** [comment]
@e1ha Where's the code? I don't see any PR..

**Comment by e1ha** [comment]
I created a PR.

**Comment by e1ha** [comment]
I added a test case with the method I mentioned in the above comment and pushed it to the same PR.

**Comment by edublancas** [comment]
sorry for the delay in the review! I'll take a look tomorrow morning

**Comment by edublancas** [comment]
ok, I took a look at the PR (https://github.com/ploomber/soorgeon/pull/72) - running the code from the generated notebooks is one option. but it's better to load the pipeline and check the structure that `soorgeon refactor` produced. I updated the first comment on this issue with sample code
