### ISSUE TITLE
Display a warning if notebooks saves files outside the output/product folder

### ISSUE THREAD

**Issue by edublancas** [ploomber/soorgeon#16]
It's possible that the original notebook already creates new files, we should show a warning if that's the case and tell the use to register them as products (include a short guide to explain how to do it)

**Comment by Wxl19980214** [comment]
Hey @edublancas , Is there any quick way to find out whether a python file will generate new files? I googled it but did not find any references. Perhaps we could just check if there is any line similar to open()? But there are too many ways for python to create a file.

**Comment by Wxl19980214** [comment]
And by registering them as products, do you mean in pipeline.yaml, add something under products?

**Comment by idomic** [comment]
> Hey @edublancas , Is there any quick way to find out whether a python file will generate new files? I googled it but did not find any references. Perhaps we could just check if there is any line similar to open()? But there are too many ways for python to create a file.

Yes that's exactly the approach, covering open, Path and the rest of the python native handlers will give us pretty good coverage to start with!

> And by registering them as products, do you mean in pipeline.yaml, add something under products?

Yes, the first step is to giving a guidance on how to add a product, the next step is adding it for them.

**Comment by Wxl19980214** [comment]
Sorry what do you mean by back burner?

**Comment by Wxl19980214** [comment]
> So for this task, we only need to warn the user that the notebook is storing files. Then we can work on automatically adding them as products.
> 
> Here's an example of what's expected.
> 
> Say my notebook contains the following:
> 
> ```python
> import pandas as pd
> 
> # cell 1
> with open('file.txt', 'w') as f:
>     f.write('text')
> 
> # cell 1
> another = open('file.txt', 'w')
> another.write('more text')
> 
> # cell 2
> df = load_data_frame()
> df.to_csv('output.csv')
> ```
> 
> We should output something like
> 
> ```
> Looks like the following lines are storing files:
> 
> with open('file.txt', 'w') as f:
>     f.write('text')
> 
> another.write('more text')
> 
> df.to_csv('output.csv')
> 
> 
> Please add them as products: [URL to show how to add products to pipeline.yaml]
> ```
> 
> To detect those things, you can use [parso](https://parso.readthedocs.io/en/latest/) (which we already use in soorgeon in the `soorgeon refactor`) logic. You can take a look at the existing code to have an idea of how it works.
> 
> Essentially, we need to traverse the code and look for places where the user might be storing files. This file can help you get an idea of how to write such feature: https://github.com/ploomber/soorgeon/blob/03229806b905e7715d1c3ee0413ff5a3bc30b71c/src/soorgeon/io.py
> 
> Since there are many ways to store files, we are ok just covering the most common ones:
> 
> * open('something')
> * `Path('something').write_text('stuff')`
> * `Path('something').write_bytes('stuff')`
> * `df.to_csv`
> * `df.to_parquet`
> 
> This is a challenging issue so feel free to ask questions!

For the last part, what's the url  for teaching users about adding the outputs to pipeline?

**Comment by idomic** [comment]
We can use [this guide](https://docs.ploomber.io/en/latest/get-started/basic-concepts.html)
