### ISSUE TITLE
Initial validation

### ISSUE THREAD

**Issue by edublancas** [ploomber/soorgeon#5]
We should validate the input notebook:

- [ ] if there are no markdown cells, show an error
- [ ] if there are only H1 headings

**Comment by idomic** [comment]
On the second bullet.
@edublancas who defines what's a few? Also what's invalid in it that we need an error? 
Imo the user and maybe it's a valid notebook for them? I assume you meant H2s since we don't support H1s currently.
Unless it's a 300 lines notebook and there's no or maybe 1-2 headers and then it make sense to output something to the user, but then it's pretty similar to https://github.com/ploomber/soorgeon/issues/47

**Comment by edublancas** [comment]
I'd say:

* Only H1 headings (regardless of the number, since we don't support them): throw an error
* Only one H2 heading, this is the same as #47

I updated the original description

**Comment by idomic** [comment]
Sounds about right, Only one H2 header will be dealt in a different PR.
The function sounds good, just validate the regex actually matches to H1s (I tried here on python and seems it doesn't https://regex101.com/).

**Comment by idomic** [comment]
> ^\s*##\s+(.+)

Is it working with this pattern?
Also I tried it online and not locally with a py console, that might be failing due to the parser.

**Comment by 94rain** [comment]
Yes, it is.

What's the input? I tried `# 1` as the input and it worked.

**Comment by idomic** [comment]
Small comment @94rain did we cover the case where no markdowns are found at all? Didn't see any in the test cases.

**Comment by 94rain** [comment]
Does `test_find_breaks_error_if_no_h1_and_h2_headers` count? `Expected notebook to have at least one markdown H2 heading.` (No H1 and H2 headers)

**Comment by idomic** [comment]
Not really since there's still markdown in the string you're checking, try having a sample with a json or plain-text

**Comment by 94rain** [comment]
> Not really since there's still markdown in the string you're checking, try having a sample with a json or plain-text

OK. Do we expect the error message to be the same as `Expected notebook to have at least one markdown H2 heading.`?

**Comment by idomic** [comment]
Yes exactly!
