### ISSUE TITLE
soorgeon clean

### ISSUE THREAD

**Issue by edublancas** [ploomber/soorgeon#50]
we should add a:

```
soorgeon clean {task-name}
```

command that cleans up notebooks. The most basic version can just apply [isort](https://pycqa.github.io/isort/), and [flake8](https://github.com/PyCQA/flake8).

A more sophisticated version can use the static analysis code that we already have to delete dead code, see  https://github.com/ploomber/soorgeon/issues/49

**Comment by 94rain** [comment]
In cli.py, I will add the `clean` command with a similar structure as `refactor` with `task-name` and `--deep` (leaving this as TODO)
* Check if `tasks` path exists, if not: => `“tasks directory not found, please refactor first!”`
* Check if `tasks/{task_name}` exists, if not => `“task {task_name} not found!”`
* Then run clean.basic_clean(): (implement `basic_clean` in a new file `clean.py`)
  * What should we use to run `yapf` and `flake8`. Do we use  `os.system`, `subprocess` or something else?

I will start to complete the implementation, but any early feedback is appreciated.

**Comment by edublancas** [comment]
my original comment was inaccurate, flake8 only lints files, it does not fix them.  let's use black (https://github.com/psf/black) as it's become the standard and many packages install it, so there's a good chance a user already has it. If black has a Python API, let's use it, if not, let's use subprocess

the main challenge here is cleaning up notebooks (ipynb files). applying isort and black to py files is trivial, but it's not for ipynb files (which we should also support). I think the best way to do it is to load the ipynb file, convert it to py file (we can use jupytext for this), apply isort and flake8, then save back as ipynb

we should add isort and black as dependencies to setup.py

**Comment by 94rain** [comment]
[Black does not have a Python API](https://black.readthedocs.io/en/stable/faq.html#does-black-have-an-api), which will require us to generate intermediate .py files for notebooks. 

I think it may be possible that users have run both `soorgeon refactor nb.ipynb` and `soorgeon refactor nb.py`. So I will clean both if there are both `{task_name}.py/.ipynb`. 

To avoid overwriting .py files refactored from nb.py, I will use [tempfile](https://docs.python.org/3/library/tempfile.html#module-tempfile) for intermediate .py files used for cleaning notebooks.

**Comment by edublancas** [comment]
sounds good
