### ISSUE TITLE
A clearer instruction on entering dev for soorgeon.

### ISSUE THREAD

**Issue by Wxl19980214** [ploomber/soorgeon#55]
We should have a more thorough instruction on how to entering dev environment, just like the ones for ploomber. It was unclear to me what do i need to do at the first place. Maybe at least telling people the process is the same as how you would contribute to ploomber

**Comment by edublancas** [comment]
great catch! I agree. can you open a PR to the [contributing.md file](https://github.com/ploomber/soorgeon/blob/main/CONTRIBUTING.md)? please add a short section describing the process and also link to ploomber's contributing.md since that one contains more details that are also applicable here
