### ISSUE TITLE
making the CI more reliable

### ISSUE THREAD

**Issue by edublancas** [ploomber/soorgeon#59]
We have a bunch of integration tests that fetch data and notebooks using Kaggle's API. However, they fail sometimes (probably because the Kaggle API isn't very reliable). See https://github.com/ploomber/soorgeon/issues/58

One solution is to use the Kaggle API once and then upload the files to an S3 bucket, then have the CI download them from S3 instead of Kaggle.

**Comment by edublancas** [comment]
including the files? the problem are the data files, some of them are a few MBs in size, I think we should store them somewhere else

**Comment by Wxl19980214** [comment]
Ok I think store in S3 bucket would be good.  I am going to list my thoughts here:
1. create a S3 bucket for notebook and data
2. write a script to download from kaggle and then upload to s3
3. run manually once to store what we have now in index.yaml to s3
4. change the CI to retrieve data from S3 instead of downloading again
5. Add another CI triggered by change in index.yaml  or in regular CI just add one check if index.yaml has been changed to run the download and upload script again.

You guys think this is a viable approach?

**Comment by idomic** [comment]
Yeah it is, I don't think you need 2, just do it manually since there are
6-7 notebooks. We have an automated script in the CI but it fails since the
kaggle API isn't stable.
I didn't get step #5 thought, elaborate?

**Comment by idomic** [comment]
You'd probably also need to make this bucket public and we shouldn't have
anything in there besides those notebooks.

**Comment by Wxl19980214** [comment]
For number 5
If someone contributed by adding a new url in [soorgeon](https://github.com/ploomber/soorgeon)/[_kaggle](https://github.com/ploomber/soorgeon/tree/main/_kaggle)/index.yaml, then we need to upload it to S3 right. So we can of course manually do it. But I am thinking maybe write a workflow triggered by changes in index.yaml. (which i dont know if it is possible to achieve) Then it runs the script to upload  newly downloaded notebook.

**Comment by Wxl19980214** [comment]
If we do this manually, i think we can all we need to change is the test right? Instead of downloading again from kaggle, we read directly from our storage repo. And if in the future someone added new urls, we also manually put it into our storage repo?

This works?

**Comment by idomic** [comment]
Yes, that's correct!
I think let's skip 5 for now, and if we see the number of notebooks scales
to double/triple then we can do that.

**Comment by idomic** [comment]
Let's try this line of thoughts:
[Try retrying](https://github.com/litl/backoff) the steps up to 3 times, if that keeps on breaking,
Try via git - sample data
Then if that fails, full data on S3

**Comment by edublancas** [comment]
👍
