### ISSUE TITLE
A utility to ensure the notebook runs

### ISSUE THREAD

**Issue by edublancas** [ploomber/soorgeon#6]
Before refactoring a notebook, the user must ensure that the original notebook runs. We should have a command to check whether it works and suggest actions if if there are some errors.

e.g., 

```sh
soorgeon run nb.ipynb
```

If the notebook fails because of a `ModuleNotFound`: suggest creating a virtualenv, and adding a `requirements.txt` with the package name

If it's an other error, show the guide for debugging notebooks

if it's a function signature, recommend downgrading some libraries

An alternative approach would be to let the user convert anyway and then help them fix the issues in the ploomber generated pipeline, this way they can leverage incremental builds for rapid iterations. we can also suggest them to add a sample parameter

**Comment by idomic** [comment]
@edublancas currently it just throws an error while refactoring right?
I'm thinking we can put it as an independent command + coupled by default as part of the refactor, thoughts?

**Comment by edublancas** [comment]
No, it doesn't throw an error. The refactoring command would pass but the code won't run.

I think this could be semi-automated: run the notebook and try to fix as many problems as we can without user intervention. The problem is that it isn't simple to implement an efficient solution. For example, imagine that the notebook doesn't have a `requirements.txt`, and it breaks on each `import package`; we could capture the import errors and add the package names to `requirements.txt` but then we'd have to restart the execution of the notebook over and over again.

I think we should leave this off right now as it isn't simple to fix.

**Comment by idomic** [comment]
As a first step, we need a command called test, to run the notebook prior to refactoring and making sure it can run without errors. Then we can have multiple options there, like matching before/after refactoring etc.

**Comment by edublancas** [comment]
A few things:

On second thought, I think we should name this `soorgeon test`. The objective of this command is to help anyone fix their notebooks until they ensure they work properly. We'll start adding a bunch of features to this command but for the moment being, let's start with the basics of running the notebook.

To execute the notebook, let's use Ploomber. It already wraps papermill and supports .py files. Essentially, we'd wrap the notebook into a pipeline of a single task. [The documentation has an example](https://docs.ploomber.io/en/latest/api/_modules/tasks/ploomber.tasks.NotebookRunner.html#ploomber-tasks-notebookrunner) of how to do it with the Python API. This would cause soorgeon to have ploomber as a dependency but I think that's fine.


> I think that what he means, usually on dependency discrepancies, there are missing functions, arguments, or it expects an extra member, AttributeError is probably a part of this set. @edublancas is that right??

Yes, attribute error is only one type of error. Another can be passing an argument that no longer exists. I'd say let's start with the executing logic and then we think of this error handling thing.

**Comment by idomic** [comment]
Maybe try using papermill to avoid circular dependency?

**Comment by edublancas** [comment]
> When I tried to run this on soorgeon/examples/exploratory/nb.ipynb, it will output that it requires a tags=["parameters"] section.

good point. i forgot that ploomber requires the parameters cell.

so yeah, let's go ahead and use papermill. you'd need to add some extra logic if the input is a .py file, you can use jupytext to convert it into ipynb https://github.com/mwouts/jupytext

please also add both papermill and jupytext to the dependencies in setup.py

**Comment by idomic** [comment]
Yeah, this route works as well!
Please add a few tests.

**Comment by 94rain** [comment]
The PR is now ready for review.

**Comment by edublancas** [comment]
I'm re-opening this since we should not use `exec`. Exec won't handle IPython magics, which are pretty common in notebooks. We need to use papermill for this.

I know that it'll make detecting errors more difficult but it's the only way to support magics.

**Comment by 94rain** [comment]
Then we can run `papermill nb.ipynb {output_notebook_path} --log-output` and check if the exception name can be found in the output instead.

How should we handle {output_notebook_path}?
Should we just abandon it (`/dev/null` for Linux/mac  or `NUL` for win)

**Comment by idomic** [comment]
> Then we can run papermill nb.ipynb {output_notebook_path} --log-output and check if the exception name can be found in the output instead.

That should work!
We can use a local location or the ~/.ploomber dir and clean this once we're done running.

> Should we just abandon it (/dev/null for Linux/mac or NUL for win)

Can you clarify?

**Comment by edublancas** [comment]
I think it'd be best to run the notebook in the same folder. because the user might be interested in looking at the traceback to debug it (and this is better than overwriting the original notebook).

Example:
* input notebook `path/to/notebook.ipynb`
* output  `path/to/notebook-soorgeon-test.ipynb`

if there's an error we can tell the user: errors happened, check `path/to/notebook-soorgeon-test.ipynb`

> check if the exception name can be found in the output instead.

yeah, I think something like:

```python
if 'ValueError' in error_string:
   # do stuff
```

will work. I'm unsure if there's a better way since we'll get the traceback as a string

**Comment by 94rain** [comment]
For `.py` files, do we also want to save `notebook-soorgeon-test.ipynb` to the current working directory?

Also we need to set a `kernel_name` for `papermill.execute_notebook()`, shall we just use `kernel_name='python3'`?

**Comment by idomic** [comment]
> For .py files, after we convert them into temp notebook files, do we also want to save the notebook execution output notebook-soorgeon-test.ipynb to the current working directory?

Good point, I think it should be controlled via the user as a parameter. I can see how it'll be useful in case it doesn't run.

> kernel_name

I think that's fine, this is how it's done in binder: Python 3 (Ipykernel)
<img width="365" alt="Screen Shot 2022-07-19 at 13 19 48" src="https://user-images.githubusercontent.com/11596985/179811200-410a2e43-3f2f-43dd-bba9-654c0d2bbe51.png">

**Comment by idomic** [comment]
@94rain @edublancas I don't see any docstring?

**Comment by edublancas** [comment]
what docstring?

**Comment by 94rain** [comment]
Does the following count?

https://github.com/ploomber/soorgeon/blob/b5012df42725f8e7238dc3146215cc5fd6889a79/src/soorgeon/cli.py#L128-L140

**Comment by idomic** [comment]
Sorry, docstring can mean tons of things.
I meant a changelog entry with a docstring for the release notes.

**Comment by edublancas** [comment]
ah. I'll edit the changelog, but yeah for other contributions let's add it
