### ISSUE TITLE
extra file?

### ISSUE THREAD

**Issue by edublancas** [ploomber/soorgeon#70]
i found this file: https://github.com/ploomber/soorgeon/blob/main/tests/please_delete_me.yaml

looks like something we should delete (?)

**Comment by idomic** [comment]
Good catch!
@Wxl19980214 ? something we missed in the code review?

**Comment by Wxl19980214** [comment]
I dont recall lol. My bad. But it sure needs to be deleted

**Comment by idomic** [comment]
Please remove and PR so we know it doesn't break anything.

**Comment by Wxl19980214** [comment]
Ok on it
